/* AntMap.java */
package org.xlattice.projmgr;

import org.xlattice.corexml.CoreXmlException ;
import org.xlattice.corexml.bind.*;
import org.xlattice.projmgr.antOM.*;

/**
 * AntMap.
 *
 * This is copyrighted material made available under the terms of
 * the XLattice License, which is included in this distribution as
 * LICENSE.txt and is also available at
 *   http://xlattice.sourceforge.net/community/license.html
 *
 * @author Jim Dixon
 */

public class AntMap {

    private static Mapping __project_Map;
    public static Mapping getProjectMap() throws CoreXmlException {
        if (__project_Map != null) 
            return __project_Map;

        Mapping __project_Map = new Mapping("project", "org.xlattice.projmgr.antOM.Project");
        __project_Map.add( new AttrBinding("basedir") );
        __project_Map.add( new AttrBinding("defaultTarget") );
        __project_Map.add( new AttrBinding("name") );
        Interface __project_projectElm_Iface = new Interface("ProjectElm", "org.xlattice.projmgr.antOM.ProjectElm", "ProjectElm");
        SubMapping __project_projectElm_property_Map = new SubMapping("Property", "org.xlattice.projmgr.antOM.Property", "ProjectElm");
        __project_projectElm_property_Map.add( new AttrBinding("name") );
        __project_projectElm_property_Map.add( new AttrBinding("value") );
        __project_projectElm_Iface.add(__project_projectElm_property_Map);
        SubMapping __project_projectElm_antComment_Map = new SubMapping("AntComment", "org.xlattice.projmgr.antOM.AntComment", "ProjectElm");
        __project_projectElm_antComment_Map.add( new AttrBinding("text") );
        __project_projectElm_Iface.add(__project_projectElm_antComment_Map);
        SubMapping __project_projectElm_target_Map = new SubMapping("Target", "org.xlattice.projmgr.antOM.Target", "ProjectElm");
        __project_projectElm_target_Map.add( new AttrBinding("description") );
        __project_projectElm_target_Map.add( new AttrBinding("if") );
        __project_projectElm_target_Map.add( new AttrBinding("name") );
        __project_projectElm_target_Map.add( new AttrBinding("unless") );
        __project_projectElm_target_Map.add( new SubElBinding("String", "depends").optional().repeats() );
        Interface __project_projectElm_target_targetElm_Iface = new Interface("TargetElm", "org.xlattice.projmgr.antOM.TargetElm", "TargetElm");
        __project_projectElm_target_targetElm_Iface.optional().repeats();
        SubMapping __project_projectElm_target_targetElm_tar_Map = new SubMapping("Tar", "org.xlattice.projmgr.antOM.Tar", "TargetElm");
        __project_projectElm_target_targetElm_tar_Map.optional().repeats();
        __project_projectElm_target_targetElm_tar_Map.add( new AttrBinding("basedir") );
        __project_projectElm_target_targetElm_tar_Map.add( new AttrBinding("destfile") );
        __project_projectElm_target_targetElm_tar_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_tar_Map.add( new AttrBinding("longfile") );
        SubMapping __project_projectElm_target_targetElm_tar_tarFileSet_Map = new SubMapping("TarFileSet", "org.xlattice.projmgr.antOM.TarFileSet");
        __project_projectElm_target_targetElm_tar_tarFileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_tar_tarFileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_tar_tarFileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_tar_tarFileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_tar_tarFileSet_Map.add(__project_projectElm_target_targetElm_tar_tarFileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_tar_Map.add(__project_projectElm_target_targetElm_tar_tarFileSet_Map);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_tar_Map);
        SubMapping __project_projectElm_target_targetElm_property_Map = new SubMapping("Property", "org.xlattice.projmgr.antOM.Property", "TargetElm");
        __project_projectElm_target_targetElm_property_Map.optional().repeats();
        __project_projectElm_target_targetElm_property_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_property_Map.add( new AttrBinding("value") );
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_property_Map);
        SubMapping __project_projectElm_target_targetElm_junit_Map = new SubMapping("Junit", "org.xlattice.projmgr.antOM.Junit", "TargetElm");
        __project_projectElm_target_targetElm_junit_Map.optional().repeats();
        __project_projectElm_target_targetElm_junit_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_junit_Map.add( new AttrBinding("errorproperty") );
        __project_projectElm_target_targetElm_junit_Map.add( new AttrBinding("failureproperty") );
        __project_projectElm_target_targetElm_junit_Map.add( new AttrBinding("fork") );
        __project_projectElm_target_targetElm_junit_Map.add( new AttrBinding("haltonerror") );
        __project_projectElm_target_targetElm_junit_Map.add( new AttrBinding("haltonfailure") );
        __project_projectElm_target_targetElm_junit_Map.add( new AttrBinding("printsummary") );
        Interface __project_projectElm_target_targetElm_junit_junitElm_Iface = new Interface("JunitElm", "org.xlattice.projmgr.antOM.JunitElm", "JunitElm");
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_batchTest_Map = new SubMapping("BatchTest", "org.xlattice.projmgr.antOM.BatchTest", "JunitElm");
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_Map.add( new AttrBinding("todir") );
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet");
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_Map.add(__project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_junit_junitElm_batchTest_Map.add(__project_projectElm_target_targetElm_junit_junitElm_batchTest_fileSet_Map);
        __project_projectElm_target_targetElm_junit_junitElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_batchTest_Map);
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_jvmarg_Map = new SubMapping("Jvmarg", "org.xlattice.projmgr.antOM.Jvmarg", "JunitElm");
        __project_projectElm_target_targetElm_junit_junitElm_jvmarg_Map.add( new AttrBinding("value") );
        __project_projectElm_target_targetElm_junit_junitElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_jvmarg_Map);
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_classpath_Map = new SubMapping("Classpath", "org.xlattice.projmgr.antOM.Classpath", "JunitElm");
        __project_projectElm_target_targetElm_junit_junitElm_classpath_Map.add( new AttrBinding("location") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_Map.add( new AttrBinding("path") );
        Interface __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_Iface = new Interface("PathlikeElm", "org.xlattice.projmgr.antOM.PathlikeElm", "PathlikeElm");
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_pathelement_Map = new SubMapping("Pathelement", "org.xlattice.projmgr.antOM.Pathelement", "PathlikeElm");
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_pathelement_Map.add( new AttrBinding("location") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_pathelement_Map.add( new AttrBinding("path") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_pathelement_Map);
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_Map = new SubMapping("TarFileSet", "org.xlattice.projmgr.antOM.TarFileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_Map.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_tarFileSet_Map);
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_Map.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_fileSet_Map);
        __project_projectElm_target_targetElm_junit_junitElm_classpath_Map.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_pathlikeElm_Iface);
        __project_projectElm_target_targetElm_junit_junitElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_classpath_Map);
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_sysproperty_Map = new SubMapping("Sysproperty", "org.xlattice.projmgr.antOM.Sysproperty", "JunitElm");
        __project_projectElm_target_targetElm_junit_junitElm_sysproperty_Map.add( new AttrBinding("key") );
        __project_projectElm_target_targetElm_junit_junitElm_sysproperty_Map.add( new AttrBinding("value") );
        __project_projectElm_target_targetElm_junit_junitElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_sysproperty_Map);
        SubMapping __project_projectElm_target_targetElm_junit_junitElm_formatter_Map = new SubMapping("Formatter", "org.xlattice.projmgr.antOM.Formatter", "JunitElm");
        __project_projectElm_target_targetElm_junit_junitElm_formatter_Map.add( new AttrBinding("classname") );
        __project_projectElm_target_targetElm_junit_junitElm_formatter_Map.add( new AttrBinding("type") );
        __project_projectElm_target_targetElm_junit_junitElm_formatter_Map.add( new AttrBinding("extension") );
        __project_projectElm_target_targetElm_junit_junitElm_formatter_Map.add( new AttrBinding("usefile") );
        __project_projectElm_target_targetElm_junit_junitElm_Iface.add(__project_projectElm_target_targetElm_junit_junitElm_formatter_Map);
        __project_projectElm_target_targetElm_junit_Map.add(__project_projectElm_target_targetElm_junit_junitElm_Iface);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_junit_Map);
        SubMapping __project_projectElm_target_targetElm_copy_Map = new SubMapping("Copy", "org.xlattice.projmgr.antOM.Copy", "TargetElm");
        __project_projectElm_target_targetElm_copy_Map.optional().repeats();
        __project_projectElm_target_targetElm_copy_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_copy_Map.add( new AttrBinding("todir") );
        __project_projectElm_target_targetElm_copy_Map.add( new AttrBinding("tofile") );
        SubMapping __project_projectElm_target_targetElm_copy_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet");
        __project_projectElm_target_targetElm_copy_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_copy_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_copy_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_copy_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_copy_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_copy_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_copy_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_copy_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_copy_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_copy_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_copy_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_copy_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_copy_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_copy_fileSet_Map.add(__project_projectElm_target_targetElm_copy_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_copy_Map.add(__project_projectElm_target_targetElm_copy_fileSet_Map);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_copy_Map);
        SubMapping __project_projectElm_target_targetElm_exec_Map = new SubMapping("Exec", "org.xlattice.projmgr.antOM.Exec", "TargetElm");
        __project_projectElm_target_targetElm_exec_Map.optional().repeats();
        __project_projectElm_target_targetElm_exec_Map.add( new AttrBinding("executable") );
        Interface __project_projectElm_target_targetElm_exec_execElm_Iface = new Interface("ExecElm", "org.xlattice.projmgr.antOM.ExecElm", "ExecElm");
        SubMapping __project_projectElm_target_targetElm_exec_execElm_env_Map = new SubMapping("Env", "org.xlattice.projmgr.antOM.Env", "ExecElm");
        __project_projectElm_target_targetElm_exec_execElm_env_Map.add( new AttrBinding("key") );
        __project_projectElm_target_targetElm_exec_execElm_env_Map.add( new AttrBinding("value") );
        __project_projectElm_target_targetElm_exec_execElm_Iface.add(__project_projectElm_target_targetElm_exec_execElm_env_Map);
        __project_projectElm_target_targetElm_exec_Map.add(__project_projectElm_target_targetElm_exec_execElm_Iface);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_exec_Map);
        SubMapping __project_projectElm_target_targetElm_zip_Map = new SubMapping("Zip", "org.xlattice.projmgr.antOM.Zip", "TargetElm");
        __project_projectElm_target_targetElm_zip_Map.optional().repeats();
        __project_projectElm_target_targetElm_zip_Map.add( new AttrBinding("basedir") );
        __project_projectElm_target_targetElm_zip_Map.add( new AttrBinding("destfile") );
        __project_projectElm_target_targetElm_zip_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_zip_Map.add( new AttrBinding("includes") );
        SubMapping __project_projectElm_target_targetElm_zip_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet");
        __project_projectElm_target_targetElm_zip_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_zip_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_zip_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_zip_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_zip_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_zip_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_zip_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_zip_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_zip_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_zip_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_zip_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_zip_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_zip_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_zip_fileSet_Map.add(__project_projectElm_target_targetElm_zip_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_zip_Map.add(__project_projectElm_target_targetElm_zip_fileSet_Map);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_zip_Map);
        SubMapping __project_projectElm_target_targetElm_javac_Map = new SubMapping("Javac", "org.xlattice.projmgr.antOM.Javac", "TargetElm");
        __project_projectElm_target_targetElm_javac_Map.optional().repeats();
        __project_projectElm_target_targetElm_javac_Map.add( new AttrBinding("debug") );
        __project_projectElm_target_targetElm_javac_Map.add( new AttrBinding("destdir") );
        __project_projectElm_target_targetElm_javac_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_javac_Map.add( new AttrBinding("includes") );
        __project_projectElm_target_targetElm_javac_Map.add( new AttrBinding("optimize") );
        __project_projectElm_target_targetElm_javac_Map.add( new AttrBinding("srcdir") );
        Interface __project_projectElm_target_targetElm_javac_javacElm_Iface = new Interface("JavacElm", "org.xlattice.projmgr.antOM.JavacElm", "JavacElm");
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_src_Map = new SubMapping("Src", "org.xlattice.projmgr.antOM.Src", "JavacElm");
        Interface __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_Iface = new Interface("PathlikeElm", "org.xlattice.projmgr.antOM.PathlikeElm", "PathlikeElm");
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_pathelement_Map = new SubMapping("Pathelement", "org.xlattice.projmgr.antOM.Pathelement", "PathlikeElm");
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_pathelement_Map.add( new AttrBinding("location") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_pathelement_Map.add( new AttrBinding("path") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_pathelement_Map);
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_Map = new SubMapping("TarFileSet", "org.xlattice.projmgr.antOM.TarFileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_Map.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_tarFileSet_Map);
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_Map.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_fileSet_Map);
        __project_projectElm_target_targetElm_javac_javacElm_src_Map.add(__project_projectElm_target_targetElm_javac_javacElm_src_pathlikeElm_Iface);
        __project_projectElm_target_targetElm_javac_javacElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_src_Map);
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_classpath_Map = new SubMapping("Classpath", "org.xlattice.projmgr.antOM.Classpath", "JavacElm");
        __project_projectElm_target_targetElm_javac_javacElm_classpath_Map.add( new AttrBinding("location") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_Map.add( new AttrBinding("path") );
        Interface __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_Iface = new Interface("PathlikeElm", "org.xlattice.projmgr.antOM.PathlikeElm", "PathlikeElm");
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_pathelement_Map = new SubMapping("Pathelement", "org.xlattice.projmgr.antOM.Pathelement", "PathlikeElm");
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_pathelement_Map.add( new AttrBinding("location") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_pathelement_Map.add( new AttrBinding("path") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_pathelement_Map);
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_Map = new SubMapping("TarFileSet", "org.xlattice.projmgr.antOM.TarFileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_Map.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_tarFileSet_Map);
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_Map.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_fileSet_Map);
        __project_projectElm_target_targetElm_javac_javacElm_classpath_Map.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_pathlikeElm_Iface);
        __project_projectElm_target_targetElm_javac_javacElm_Iface.add(__project_projectElm_target_targetElm_javac_javacElm_classpath_Map);
        __project_projectElm_target_targetElm_javac_Map.add(__project_projectElm_target_targetElm_javac_javacElm_Iface);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_javac_Map);
        SubMapping __project_projectElm_target_targetElm_javadoc_Map = new SubMapping("Javadoc", "org.xlattice.projmgr.antOM.Javadoc", "TargetElm");
        __project_projectElm_target_targetElm_javadoc_Map.optional().repeats();
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("author").optional() );
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("destdir") );
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("overview").optional() );
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("package").optional() );
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("packagenames") );
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("protected").optional() );
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("public").optional() );
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("sourcepath") );
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("use").optional() );
        __project_projectElm_target_targetElm_javadoc_Map.add( new AttrBinding("version").optional() );
        Interface __project_projectElm_target_targetElm_javadoc_javadocElm_Iface = new Interface("JavadocElm", "org.xlattice.projmgr.antOM.JavadocElm", "JavadocElm");
        SubMapping __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_Map = new SubMapping("Classpath", "org.xlattice.projmgr.antOM.Classpath", "JavadocElm");
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_Map.add( new AttrBinding("location") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_Map.add( new AttrBinding("path") );
        Interface __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_Iface = new Interface("PathlikeElm", "org.xlattice.projmgr.antOM.PathlikeElm", "PathlikeElm");
        SubMapping __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_pathelement_Map = new SubMapping("Pathelement", "org.xlattice.projmgr.antOM.Pathelement", "PathlikeElm");
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_pathelement_Map.add( new AttrBinding("location") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_pathelement_Map.add( new AttrBinding("path") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_pathelement_Map);
        SubMapping __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_Map = new SubMapping("TarFileSet", "org.xlattice.projmgr.antOM.TarFileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_Map.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_tarFileSet_Map);
        SubMapping __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_Map.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_fileSet_Map);
        __project_projectElm_target_targetElm_javadoc_javadocElm_classpath_Map.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_pathlikeElm_Iface);
        __project_projectElm_target_targetElm_javadoc_javadocElm_Iface.add(__project_projectElm_target_targetElm_javadoc_javadocElm_classpath_Map);
        __project_projectElm_target_targetElm_javadoc_Map.add(__project_projectElm_target_targetElm_javadoc_javadocElm_Iface);
        SubMapping __project_projectElm_target_targetElm_javadoc_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet");
        __project_projectElm_target_targetElm_javadoc_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_javadoc_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_javadoc_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_javadoc_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_javadoc_fileSet_Map.add(__project_projectElm_target_targetElm_javadoc_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_javadoc_Map.add(__project_projectElm_target_targetElm_javadoc_fileSet_Map);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_javadoc_Map);
        SubMapping __project_projectElm_target_targetElm_delete_Map = new SubMapping("Delete", "org.xlattice.projmgr.antOM.Delete", "TargetElm");
        __project_projectElm_target_targetElm_delete_Map.optional().repeats();
        __project_projectElm_target_targetElm_delete_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_delete_Map.add( new AttrBinding("file") );
        SubMapping __project_projectElm_target_targetElm_delete_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet");
        __project_projectElm_target_targetElm_delete_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_delete_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_delete_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_delete_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_delete_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_delete_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_delete_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_delete_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_delete_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_delete_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_delete_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_delete_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_delete_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_delete_fileSet_Map.add(__project_projectElm_target_targetElm_delete_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_delete_Map.add(__project_projectElm_target_targetElm_delete_fileSet_Map);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_delete_Map);
        SubMapping __project_projectElm_target_targetElm_mkdir_Map = new SubMapping("Mkdir", "org.xlattice.projmgr.antOM.Mkdir", "TargetElm");
        __project_projectElm_target_targetElm_mkdir_Map.optional().repeats();
        __project_projectElm_target_targetElm_mkdir_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_mkdir_Map);
        SubMapping __project_projectElm_target_targetElm_antComment_Map = new SubMapping("AntComment", "org.xlattice.projmgr.antOM.AntComment", "TargetElm");
        __project_projectElm_target_targetElm_antComment_Map.optional().repeats();
        __project_projectElm_target_targetElm_antComment_Map.add( new AttrBinding("text") );
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_antComment_Map);
        SubMapping __project_projectElm_target_targetElm_tstamp_Map = new SubMapping("Tstamp", "org.xlattice.projmgr.antOM.Tstamp", "TargetElm");
        __project_projectElm_target_targetElm_tstamp_Map.optional().repeats();
        SubMapping __project_projectElm_target_targetElm_tstamp_format_Map = new SubMapping("Format", "org.xlattice.projmgr.antOM.Format");
        __project_projectElm_target_targetElm_tstamp_format_Map.add( new AttrBinding("pattern") );
        __project_projectElm_target_targetElm_tstamp_format_Map.add( new AttrBinding("property") );
        __project_projectElm_target_targetElm_tstamp_Map.add(__project_projectElm_target_targetElm_tstamp_format_Map);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_tstamp_Map);
        SubMapping __project_projectElm_target_targetElm_jar_Map = new SubMapping("Jar", "org.xlattice.projmgr.antOM.Jar", "TargetElm");
        __project_projectElm_target_targetElm_jar_Map.optional().repeats();
        __project_projectElm_target_targetElm_jar_Map.add( new AttrBinding("basedir") );
        __project_projectElm_target_targetElm_jar_Map.add( new AttrBinding("destfile") );
        __project_projectElm_target_targetElm_jar_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_jar_Map.add( new AttrBinding("manifest") );
        Interface __project_projectElm_target_targetElm_jar_pathlikeElm_Iface = new Interface("PathlikeElm", "org.xlattice.projmgr.antOM.PathlikeElm", "PathlikeElm");
        SubMapping __project_projectElm_target_targetElm_jar_pathlikeElm_pathelement_Map = new SubMapping("Pathelement", "org.xlattice.projmgr.antOM.Pathelement", "PathlikeElm");
        __project_projectElm_target_targetElm_jar_pathlikeElm_pathelement_Map.add( new AttrBinding("location") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_pathelement_Map.add( new AttrBinding("path") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_jar_pathlikeElm_pathelement_Map);
        SubMapping __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_Map = new SubMapping("TarFileSet", "org.xlattice.projmgr.antOM.TarFileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_Map.add(__project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_jar_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_jar_pathlikeElm_tarFileSet_Map);
        SubMapping __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_Map = new SubMapping("FileSet", "org.xlattice.projmgr.antOM.FileSet", "PathlikeElm");
        __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_Map.add( new AttrBinding("dir") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_Map.add( new AttrBinding("excludes") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_Map.add( new AttrBinding("file") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_Map.add( new AttrBinding("includes") );
        Interface __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_Iface = new Interface("FileSetElm", "org.xlattice.projmgr.antOM.FileSetElm", "FileSetElm");
        SubMapping __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_exclude_Map = new SubMapping("Exclude", "org.xlattice.projmgr.antOM.Exclude", "FileSetElm");
        __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_exclude_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_exclude_Map);
        SubMapping __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_include_Map = new SubMapping("Include", "org.xlattice.projmgr.antOM.Include", "FileSetElm");
        __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_include_Map.add( new AttrBinding("name") );
        __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_Iface.add(__project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_include_Map);
        __project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_Map.add(__project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_fileSetElm_Iface);
        __project_projectElm_target_targetElm_jar_pathlikeElm_Iface.add(__project_projectElm_target_targetElm_jar_pathlikeElm_fileSet_Map);
        __project_projectElm_target_targetElm_jar_Map.add(__project_projectElm_target_targetElm_jar_pathlikeElm_Iface);
        __project_projectElm_target_targetElm_Iface.add(__project_projectElm_target_targetElm_jar_Map);
        __project_projectElm_target_Map.add(__project_projectElm_target_targetElm_Iface);
        __project_projectElm_Iface.add(__project_projectElm_target_Map);
        __project_Map.add(__project_projectElm_Iface);
        __project_Map.join();

        return __project_Map;
    }

}
